// app/layout.tsx
import type { Metadata } from "next";
// 假設您的字體導入方式正確
import { Geist, Geist_Mono } from "next/font/google"; 
import "./globals.css";
// 確保路徑正確
import MenuLayout from '../components/MenuLayout'; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 修正點 1：MenuLayout 必須包裹 children */}
        <MenuLayout>
            {/* 修正點 2：將頁面內容 {children} 傳遞給 MenuLayout */}
            {children}
        </MenuLayout>
      </body>
    </html>
  );
}